### PR TITLE
Primary key fix, dependency and specs fix for inner test app

### PR DESCRIPTION
**Pull request by xfynx**
+ Fixed primary key (which was presented in previous PRs)
+ Fixed specs and some bugs remains from rails3 to rails4 migration.
The problems was caused by old inner test_app, which is used for smoke testing inside gem, so i fixed them.

+ Added gemfile.lock into repository for successful deployment at travis-ci (mainly on ruby 1.9.3)

### CODE REVIEW

**Comment by xfynx** [comment]
travis config need to be updated

**Comment by xfynx** [comment]
travis config need to be updated

**Comment by xfynx** [comment]
I don't know why your travis failed to deploy at 1.9.3, mine as you can see in this branch are okay
https://travis-ci.org/xfynx/activeadmin-mongoid/builds/198804498

**Comment by boie0025** [comment]
@xfynx We've since updated a lot of the libraries used in this gem.  Do you have any interest in merging master in to this branch and cleaning that up, or perhaps creating a top level branch for legacy applications still using libraries relevant to this PR?

**Comment by xfynx** [comment]
@boie0025 commits related more to legacy version, so yes, second variant is more preferable

**Comment by boie0025** [comment]
OK I will merge into rails4 branch.

**Comment by boie0025** [comment]
Perfect, thanks @xfynx!

**Pull request merged**
