### PR TITLE
Introduce rubocop

### PR DESCRIPTION
**Pull request by grzegorz-jakubiak**

### CODE REVIEW

**Comment by grzegorz-jakubiak** [comment]
No idea why Lint CI errors out 🤔 I wanted to add `bundle exec rubocop` after tests to `.travis.yml`. I guess we've got Lint CI configured for every repository that includes `.rubocop.yml`. @deivid-rodriguez any ideas?

**Comment by deivid-rodriguez** [comment]
@timoschilling added this service to all repos in the organization at some point, but I don't think he's maintaining it any longer so I believe it's fine to disable it / remove it.

**Comment by timoschilling** [comment]
Remove it. It’s no longer maintained. GH actions killed the business model

**Comment by deivid-rodriguez** [comment]
I removed it, I think the check should stop showing up in a bit.

**Comment by deivid-rodriguez** [comment]
Thanks @timoschilling! :+1:

**Comment by grzegorz-jakubiak** [comment]
@timoschilling and @deivid-rodriguez thanks guys! I added `bundle exec rubocop` to `.travis.yml`. All green now and ready for review.

**Pull request merged**
