### PR TITLE
Prepare for 0.9.0

### PR DESCRIPTION
**Pull request by boie0025**
* Bump ActiveAdmin version
* Bump Rails version
* Bump Devise version
From @deivid-rodriguez 
* Remove unused gemfile and lockfile
* Remove unused stuff from Gemfile
* Use https source to prevent bundler warning
```
The git source
`git://github.com/activerecord-hackery/ransack-mongoid.git` uses the
`git` protocol, which transmits data without encryption. Disable this
warning with `bundle config git.allow_insecure true`, or switch to the
`https` protocol to keep your data secure.
```
* Move `pry-rails` to main group
* bundle update
* Fix RSpec deprecation warning
```
Requiring `rspec/autorun` when running RSpec via the `rspec` command is
deprecated. Called from
/path/to/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in
`require'.
```

### CODE REVIEW

**Comment by boie0025** [comment]
Thoughts on waiting for a PR for #138 ?

**Comment by grzegorz-jakubiak** [comment]
I'd include rubygems badge as well 😉

**Comment by boie0025** [comment]
@grzegorz-jakubiak Will you please add that and push to this branch?

**Comment by grzegorz-jakubiak** [comment]
@boie0025 done

**Pull request merged**
